import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const jetBrains = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Shaaf Shahzad",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="w-full h-full">
			<body
				className={`${jetBrains.className} h-full w-full box-border p-20 flex flex-row bg-gradient`}
			>
				<Sidebar />
				<div className="w-3/5 overflow-y-auto flex justify-center">
					{children}
				</div>
			</body>
		</html>
	);
}
