import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const jetBrains = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shaaf Shahzad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jetBrains.className}>
        <div className="border border-black h-full w-full box-border p-20 flex flex-row bg-gradient">
          <div className="h-full w-1/2 flex flex-col justify-start items-start">
            <div className="">
              <p className="text-5xl font-thin -ml-1">Shaaf Shahzad</p>
              <p className="font-thin text-xs mt-2 text-left subheader">
                full time student // part time developer
              </p>
            </div>
            <div className="">
              <Navbar />
            </div>
            <div className="flex h-full w-1/2 justify-start items-end">
              <div className="flex flex-row justify-between w-1/2 mt-10">
                <a
                  href="https://github.com/shaafshahzad"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <img
                    src="/github.png"
                    className="w-6 filter-e2e8f0"
                    alt="GitHub"
                  />
                </a>
                <a href="https://www.linkedin.com/in/shaafshahzad">
                  <img
                    src="/linkedin.png"
                    className="w-6 filter-e2e8f0"
                    alt="LinkedIn"
                  />
                </a>
                <a
                  href="https://www.instagram.com/shaafshahzad"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <img
                    src="/instagram.png"
                    className="w-6 filter-e2e8f0"
                    alt="Instagram"
                  />
                </a>{" "}
              </div>
            </div>
          </div>
          <div className="w-1/2 overflow-y-auto ">{children}</div>
        </div>
      </body>
    </html>
  );
}
